# This file contains just card definitions. See also `CardConfig.gd`

extends Reference

const SET = "Core Set"
const CARDS := {
	"Circle Shader": {
		"Type": "Shader",
		"Tags": [],
		"Abilities": "Create them circles",
		"Time": 0,
		"Value": 1,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 0,
		"motivation_req": 0,
	},
	"Advanced Shader": {
		"Type": "Shader",
		"Tags": [],
		"Abilities": "Some tricky stuff",
		"Time": 1,
		"Value": 2,
		"Kudos": 0,
		"skill_req": 1,
		"cred_req": 0,
		"motivation_req": 0,
	},
	"Newbie Tutor": {
		"Type": "Resource",
		"Tags": ["Tutor"],
		"Abilities": "All skill_req 1 shaders are reduced to 0",
		"Time": 1,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 0,
		"motivation_req": 0,
	},
	"Cheerleader": {
		"Type": "Resource",
		"Tags": ["Collaborator"],
		"Abilities": "After recruiting this tutor, lose 1 cred. " \
				+ "You win extra 1 cred for winning a tournament",
		"Time": 1,
		"Value": 2,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 1,
		"motivation_req": 4,
	},
	"Guru": {
		"Type": "Resource",
		"Tags": ["Tutor"],
		"Abilities": "All skill_req 4+ shaders are reduced by 1",
		"Time": 2,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 3,
		"cred_req": 4,
		"motivation_req": 0,
	},
	"Chiptunes Musician": {
		"Type": "Resource",
		"Tags": ["Collaborator"],
		"Abilities": "Pay 4 Kudos to play.\n" \
				+ "Increase the value of your Demo this round by 2. "\
				+ "Discard after this round ends",
		"Time": 2,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 1,
		"motivation_req": 0,
	},
	"Graphics Artist": {
		"Type": "Resource",
		"Tags": ["Collaborator"],
		"Abilities": "Pay 4 Kudos to play.\n" \
				+ "If you use at least 3 shaders of skill_req 1, "\
				+ "increase your Demo value by 2."\
				+ "Discard after this round ends",
		"Time": 2,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 2,
		"motivation_req": 0,
	},
	"Git": {
		"Type": "Resource",
		"Tags": ["Knowledge"],
		"Abilities": "Events that make you lose time, make you lose 1 less time. "\
				+ "After your fourth shader to your demo, gain 1 time.",
		"Time": 1,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 0,
		"motivation_req": 0,
	},
	"IRC Mod": {
		"Type": "Resource",
		"Tags": ["Volunteering"],
		"Abilities": "Comes into the game with 12 Kudos tokens\n\n"\
				+ "1 Time: Take 2 Kudos tokens from this card. "\
				+ "When it has no more kudos tokens, discard it.",
		"Time": 1,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 1,
		"motivation_req": 7,
	},
	"Get Some IRC Advice": {
		"Type": "Prep",
		"Tags": [],
		"Abilities": "Play a Shader as if you had +1 skill",
		"Time": 1,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 0,
		"motivation_req": 0,
	},
	"Google-Fu!": {
		"Type": "Prep",
		"Tags": [],
		"Abilities": "Draw 3 cards",
		"Time": 2,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 0,
		"motivation_req": 0,
	},
	"Post Some Progress": {
		"Type": "Prep",
		"Tags": [],
		"Abilities": "Gain 1 Cred",
		"Time": 1,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 0,
		"cred_req": 0,
		"motivation_req": 0,
	},
	"Help out Some Newbs": {
		"Type": "Prep",
		"Tags": [],
		"Abilities": "Gain 3 Kudos",
		"Time": 1,
		"Value": 0,
		"Kudos": 0,
		"skill_req": 1,
		"cred_req": 0,
		"motivation_req": 0,
	},
}
