extends DeckBuilder

onready var back_button = $VBC/HBC/MC/CurrentDeck/Buttons/Back

# Extend this class and call this function, when your game has a value field
# Which is suposed to be autogenerated in some fashion.
# warning-ignore:unused_argument
func generate_value(property: String, card_properties: Dictionary):
	if property == 'Value':
		return(FFCard.generate_shader_value(
			card_properties.Time, 
			card_properties.skill_req, 
			card_properties.get("_abilities_power",0)))
	else:
		return('')
