extends Reference

const CONTENTS = {
	"Simple Colours": 3,
	"Light": 3,
	"Fractal Pyramid": 3,
	"Mandelbrot": 3,
	"Cloud": 3,
	"Strings": 3,
	"Newbie Tutor": 2,
#	"Cheerleader": 2,
	"Chiptunes Musician": 2,
	"Graphics Artist": 1,
	"Google-Fu!": 3,
	"Get Some Advice": 3,
	"Discord Mod": 2,
	"Post Some Progress": 3,
	"Social Networking": 3,
	"Private Forum Mod": 1,
	"Hacking Buddy": 2,
	"Search Engine Expertise": 2,
#	"Twister": 10,
#	"Seascape": 20,
#	"Voronoi Column Tracing": 0,
#	"Fractal Tiling": 10,
}
